### ISSUE TITLE
Update readme 

### ISSUE THREAD

**Issue by UmangThapliyal** [deep-compute/jslogger#19]
We have made certain changes which need to be updated in the doc 
- [x]  Npm pakcage installation
- [x]  Usage
- [x]  Remove deprecated axios 
- [x]  dependency updated

**Comment by UmangThapliyal** [comment]
@sundarrajan78 here we can take help from developer and update readme

**Comment by sundarrajan78** [comment]
@UmangThapliyal Post update

**Comment by UmangThapliyal** [comment]
will give initial readme today

**Comment by sundarrajan78** [comment]
> will give initial readme today

@UmangThapliyal Post update

**Comment by sundarrajan78** [comment]
@UmangThapliyal will take this up later this week

**Comment by sundarrajan78** [comment]
@UmangThapliyal Post update

**Comment by sundarrajan78** [comment]
@UmangThapliyal Post update

**Comment by UmangThapliyal** [comment]
@sundarrajan78 this is low prio for now

**Comment by sundarrajan78** [comment]
@UmangThapliyal What is pending here?

**Comment by UmangThapliyal** [comment]
@sundarrajan78 the readme is outdated we have to remove it and add new readme

**Comment by sundarrajan78** [comment]
@UmangThapliyal Please wrap it up this week and close this issue.

**Comment by sundarrajan78** [comment]
@purushothaman-source Post update

**Comment by purushothaman-source** [comment]
updated  readme ..
