### ISSUE TITLE
remove outdated examples and add example for react or node 

### ISSUE THREAD

**Issue by UmangThapliyal** [deep-compute/jslogger#21]
we had python example previously in jslogger we need to remove it and then add the example with js

**Comment by sundarrajan78** [comment]
@UmangThapliyal Post update

**Comment by sundarrajan78** [comment]
Low priority

**Comment by UmangThapliyal** [comment]
low prio will attempt next week

**Comment by sundarrajan78** [comment]
@UmangThapliyal @purushothaman-source Post update

**Comment by sundarrajan78** [comment]
@purushothaman-source Post update

**Comment by purushothaman-source** [comment]
pr merged
