### ISSUE TITLE
Pass headers with log

### ISSUE THREAD

**Issue by ManishaBayya** [deep-compute/jslogger#24]

**Comment by UmangThapliyal** [comment]
will check this today

**Comment by sundarrajan78** [comment]
@UmangThapliyal Can you prioritise this week?

**Comment by rajinish01** [comment]
abc

**Comment by rajinish01** [comment]
abc

**Comment by ManishaBayya** [comment]
> abc

@rajinish01 Is this added by mistake?

**Comment by sundarrajan78** [comment]
@ManishaBayya It should be while testing for taskdomo. You can ignore it.

@rajinish01 Never use repos other than ci_test for taskdomo testing.

**Comment by sundarrajan78** [comment]
Assigning to @purushothaman-source

**Comment by prashanthellina** [comment]
@purushothaman-source What is the effort involved in doing this?

**Comment by purushothaman-source** [comment]
@prashanthellina  this was done 
![Screenshot from 2022-10-12 06-31-06](https://user-images.githubusercontent.com/72643364/195225215-487b1ab8-24f4-4e58-9e15-fc88f8538aa2.png)

**Comment by prashanthellina** [comment]
Thank you @purushothaman-source
