### ISSUE TITLE
add condition for empty array 

### ISSUE THREAD

**Issue by UmangThapliyal** [deep-compute/jslogger#34]
when we are running the service as node we are getting it as array and thats why condition is not met we need to add condition to check and close once the length is 0

**Comment by sundarrajan78** [comment]
@UmangThapliyal Post update

**Comment by sundarrajan78** [comment]
@UmangThapliyal Post update. I have added @ColinKotar and @purushothaman-source to deepcompute org. Please reassign tasks to them

**Comment by sundarrajan78** [comment]
@UmangThapliyal Post update. I have added @ColinKotar and @purushothaman-source to deepcompute org. Please reassign tasks to them

**Comment by UmangThapliyal** [comment]
@sundarrajan78 this issue is resolved so we can close this
