### ISSUE TITLE
jslogger throws an error when a ajax call is aborted

### ISSUE THREAD

**Issue by jaswanth098** [deep-compute/jslogger#7]

**Comment by jaswanth098** [comment]
- The error is raised when ajax call are being aborted, we have success and failure condition for ajax call in jslogger in which we log the size of response, there won't be a response when ajax call is aborted.
- going to fix this

**Comment by bajibabu9** [comment]
@jaswanth098 @BRRavisankar The problem still exists, it's throwing errors while doing abort. Please check it in all places and fix asap. Thank you
Ref: https://github.com/deep-compute/nference/issues/3012

**Comment by jaswanth098** [comment]
This is fixed and merged to master closing this
